CodeSystem: HL7Workgroup
Id: hl7-work-group
Title: "HL7Workgroup"
Description: "An HL7 administrative unit that owns artifacts in the FHIR specification."
* ^meta.lastUpdated = "2020-04-09T21:10:28.568+00:00"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:2.16.840.1.113883.4.642.1.1277"
* ^version = "7.0.0"
* ^status = #active
* ^experimental = false
* ^date = "2020-04-09T21:10:28+00:00"
* ^publisher = "Health Level Seven International"
* ^contact.telecom[0].system = #url
* ^contact.telecom[=].value = "http://hl7.org/"
* ^contact.telecom[+].system = #email
* ^contact.telecom[=].value = "hq@HL7.org"
* ^copyright = "This material derives from the HL7 Terminology (THO). THO is copyright ©1989+ Health Level Seven International and is made available under the CC0 designation. For more licensing information see: https://terminology.hl7.org/license"
* ^caseSensitive = true
* ^valueSet = "http://terminology.hl7.org/ValueSet/hl7-work-group"
* ^content = #complete
* ^property.code = #status
* ^property.uri = "http://hl7.org/fhir/concept-properties#status"
* ^property.description = "Designation of a concept's state. Normally is not populated unless the state is retired."
* ^property.type = #code
* #aid "Application Implementation and Design" "Application Implementation and Design (http://www.hl7.org/Special/committees/java/index.cfm)."
* #arden "Arden Syntax" "Arden Syntax (http://www.hl7.org/Special/committees/arden/index.cfm)"
* #att "Clinical Attachments" "Clinical Attachments Workgroup (inactive since mid-2018; work subsumed by Structured Documents and Financial Management).  Retained for backwards-compatibility only."
* #brr "Biomedical Research and Regulation" "Biomedical Research and Regulation (http://www.hl7.org/Special/committees/rcrim/index.cfm)."
* #cbcc "Community Based Collaborative Care" "Community Based Collaborative Care (http://www.hl7.org/Special/committees/cbcc/index.cfm)."
* #cdamg "CDA Management Group" "CDA Management Group (http://www.hl7.org/Special/committees/cdamg/index.cfm)"
* #cds "Clinical Decision Support" "Clinical Decision Support (http://www.hl7.org/Special/committees/dss/index.cfm)."
* #cg "Clinical Genomics" "Clinical Genomics (http://www.hl7.org/Special/committees/clingenomics/index.cfm)."
* #cgp "Cross-Group Projects" "Cross-Group Projects (http://www.hl7.org/Special/committees/cgp/index.cfm)"
* #cic "Clinical Interoperability Council" "Clinical Interoperability Council (http://www.hl7.org/Special/committees/cic/index.cfm)."
* #cimi "Clinical Information Modeling Initiative" "Clinical Information Modeling Initiative (http://www.hl7.org/Special/committees/cimi/index.cfm)"
* #claims "Payer/Provider Information Exchange Work Group" "Payer/Provider Information Exchange Work Group (http://www.hl7.org/Special/committees/claims/index.cfm)"
* #cqi "Clinical Quality Information" "Clinical Quality Information (http://www.hl7.org/Special/committees/cqi/index.cfm)."
* #dev "Health Care Devices" "Health Care Devices (http://www.hl7.org/Special/committees/healthcaredevices/index.cfm)."
* #ehr "Electronic Health Records" "Electronic Health Records (http://www.hl7.org/special/committees/ehr/index.cfm)."
* #ec "Emergency Care" "Emergency Care (http://www.hl7.org/Special/committees/emergencycare/index.cfm)"
* #fhir "FHIR Infrastructure" "FHIR Infrastructure (http://www.hl7.org/Special/committees/fiwg/index.cfm)."
* #fmg "FHIR Management Group" "FHIR Management Group (http://www.hl7.org/Special/committees/fhirmg/index.cfm)"
* #fm "Financial Management" "Financial Management (http://www.hl7.org/Special/committees/fm/index.cfm)."
* #hsi "Health Standards Integration" "Health Standards Integration (http://www.hl7.org/Special/committees/hsi/index.cfm)."
* #hsswg "Human and Social Services" "Human and Social Services (http://www.hl7.org/Special/committees/hsswg/index.cfm)"
* #hta "Terminology Authority" "Terminology Authority (http://www.hl7.org/Special/committees/termauth/index.cfm)"
* #ictc "Conformance" "Conformance (http://www.hl7.org/Special/committees/ictc/index.cfm)"
* #ii "Imaging Integration" "Imaging Integration (http://www.hl7.org/Special/committees/imagemgt/index.cfm)."
* #inm "Infrastructure And Messaging" "Infrastructure And Messaging (http://www.hl7.org/special/committees/inm/index.cfm)."
* #its "Implementable Technology Specifications" "Implementable Technology Specifications (http://www.hl7.org/special/committees/xml/index.cfm)."
* #lhs "Learning Health Systems" "Learning Health Systems (http://www.hl7.org/Special/committees/lhs/index.cfm)"
* #mnm "Modeling and Methodology" "Modeling and Methodology (http://www.hl7.org/Special/committees/mnm/index.cfm)."
* #mobile "Mobile Health" "Mobile Health (http://www.hl7.org/Special/committees/mobile/index.cfm)"
* #oo "Orders and Observations" "Orders and Observations (http://www.hl7.org/Special/committees/orders/index.cfm)."
* #pa "Patient Administration" "Patient Administration (http://www.hl7.org/Special/committees/pafm/index.cfm)."
* #pc "Patient Care" "Patient Care (http://www.hl7.org/Special/committees/patientcare/index.cfm)."
* #pher "Public Health and Emergency Response" "Public Health and Emergency Response (http://www.hl7.org/Special/committees/pher/index.cfm)."
* #phx "Pharmacy" "Pharmacy (http://www.hl7.org/Special/committees/medication/index.cfm)."
* #sd "Structured Documents" "Structured Documents (http://www.hl7.org/Special/committees/structure/index.cfm)."
* #sec "Security" "Security (http://www.hl7.org/Special/committees/secure/index.cfm)."
* #ti "Terminology Infrastructure" "Terminology Infrastructure (http://www.hl7.org/Special/committees/Vocab/index.cfm)"
* #ti ^property.code = #status
* #ti ^property.valueCode = #retired
* #tsmg "Terminology Services Management Group (TSMG)" "Terminology Services Management Group (TSMG) (http://www.hl7.org/Special/committees/tsmg/index.cfm)"
* #us "US Realm Steering Committee" "US Realm Taskforce (http://www.hl7.org/Special/committees/usrealm/index.cfm)."
* #v2 "V2 Management Group" "V2 Management Group (http://www.hl7.org/Special/committees/v2management/index.cfm)"
* #vocab "Terminology Infrastructure" "Terminology Infrastructure (http://www.hl7.org/Special/committees/Vocab/index.cfm)."