ValueSet: Observation.valueCodeableConceptSpecific
Title: "Value set specific for Observation specific value CodeableConcept"
Description: "Value set specific for Observation specific value CodeableConcept"
* ^url = "http://terminology.kemkes.go.id/ValueSet/Observation.valueCodeableConceptSpecific"
* include codes from system http://loinc.org
* include codes from system http://loinc.org where concept is-a #LA17718-0 "Sinus rhythm"
* include codes from system http://loinc.org where concept is-a #LA17099-5 "Sinus tachycardia"
* include codes from system http://loinc.org where concept is-a #LA17098-7 "Sinus bradycardia"
* include codes from system http://loinc.org where concept is-a #LA17091-2 "Left bundle branch block"
* include codes from system http://loinc.org where concept is-a #LA17084-7 "Atrial fibrillation"
* include codes from system http://loinc.org where concept is-a #LA17099-5 "Supraventricular tachycardia"
* include codes from system http://loinc.org where concept is-a #LA17708-1 "Ventricular tachycardia with pulse"
* include codes from system http://loinc.org where concept is-a #LA17074-8 "Ventricular tachycardia-pulseless"
* include codes from system http://loinc.org where concept is-a #LA17086-2 "AV block-1st degree"
* include codes from system http://loinc.org where concept is-a #LA17087-0 "AV block-2nd degree-type 1"
* include codes from system http://loinc.org where concept is-a #LA17088-8 "AV block-2nd degree-type 2"
* include codes from system http://loinc.org where concept is-a #LA17089-6 "AV block-3rd degree"
* include codes from system http://loinc.org where concept is-a #LA17093-8 "Paced rhythm"
* include codes from system http://snomed.info/sct where concept descendant-of #118956008 "Body structure, altered from its original anatomical structure (morphologic abnormality)"
* include codes from system http://snomed.info/sct where concept descendant-of #12738006 "Brain structure (body structure)"
* include codes from system http://snomed.info/sct where concept is-a #10003008 "Unspecified"
* include codes from system http://snomed.info/sct where concept descendant-of #432504007 "Cerebral infarction (disorder)"
* include codes from system http://snomed.info/sct where concept is-a #164895002 "Electrocardiographic ventricular tachycardia"
* include codes from system http://snomed.info/sct where concept is-a #164896001 "Electrocardiographic ventricular fibrillation"
* include codes from system http://snomed.info/sct where concept is-a #705008001 "Anterior ST segment elevation"
* include codes from system http://snomed.info/sct where concept is-a #705012007 "Anterior and lateral ST segment elevation"
* include codes from system http://snomed.info/sct where concept is-a #164868007 "Anteroseptal infarction on electrocardiogram"
* include codes from system http://snomed.info/sct where concept is-a #705007006 "Inferior ST segment elevation"
* include codes from system http://snomed.info/sct where concept is-a #705010004 "Posterior ST segment elevation"
* include codes from system http://snomed.info/sct where concept is-a #261665006 "Unknown"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OV000367 "Subkorteks"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OCV000001 "LBBB baru"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OCV000003 "Tidak ada perubahan akut"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OCV000004 "ST elevasi tidak dapat ditentukan"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OV000368 "LBBB baru"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OV000369 "Tidak ada perubahan akut"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OV000370 "ST elevasi tidak dapat ditentukan"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OV000401 "Benzatin Penicillin G (BPG) intramuskular"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OV000402 "Penicillin oral"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OV000403 "Erythromycin oral"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OV000407 "Statin Intensitas Tinggi"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OV000408 "Statin Intensitas Sedang"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OV000409 "Statin Intensitas Rendah"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #X099770 "Rifampisin sensitive"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #X099771 "Rifampisin resistan"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #X099772 "Rifampisin indeterminate"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #X099773 "Indeterminate (IDT)"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #X099774 "Ress Inffered (RI)"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/examination where concept is-a #X099770 "Rifampisin sensitive"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/examination where concept is-a #X099771 "Rifampisin resistan"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/examination where concept is-a #X099772 "Rifampisin indeterminate"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/examination where concept is-a #X099773 "Indeterminate (IDT)"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/examination where concept is-a #X099774 "Ress Inffered (RI)"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OV000371 "Terjadi Multiple Perdarahan"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OV000372 "Tidak Terjadi Multiple Perdarahan"