Alias: SCT = http://snomed.info/sct
Alias: KCT = http://terminology.kemkes.go.id/CodeSystem/clinical-term

ValueSet: Observation.interpretation
Title: "Value set specific for Observation Code"
Description: "Value set specific for Observation Code"
* ^url = "http://terminology.kemkes.go.id/ValueSet/Observation.interpretation"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000001 "Gizi Buruk"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000002 "Gizi Kurang"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000003 "Gizi Baik"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000004 "Risiko Gizi Lebih"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000005 "Gizi Lebih"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000006 "Obesitas"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000007 "Berat Badan Sangat Kurang"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000008 "Berat Badan Kurang"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000009 "Berat Badan Normal"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000010 "Risiko Berat Badan Lebih"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000011 "Sangat Pendek"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000012 "Pendek"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000013 "Normal"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000014 "Tinggi"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000015 "Normocephaly"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000016 "Sesuai Usia"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000017 "Tidak Sesuai Usia"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000018 "Kurang Energi Kronis (KEK)"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000019 "Mild to No Pain"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000020 "Mild to Moderate Pain"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000021 "7 - 11 (Risiko rendah)"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000022 "> 12 (Risiko tinggi)"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000023 "0 - 89 (Risiko rendah)"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000024 "> 90 (Risiko tinggi)"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000025 "Tidak Normal"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000026 "0 - 24 (Risiko rendah)"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000027 "25 - 44 (Risiko sedang)"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000028 "≥ 45 (Risiko tinggi)"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000029 "Kondisi Gigi Baik"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000030 "Kondisi Gigi Cukup Baik"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000031 "Kondisi Gigi Buruk"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000032 "Anemia ringan"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000033 "Anemia sedang"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000034 "Anemia berat"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000035 "Risiko Kurang Energi Kronis (KEK)"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000036 "Tingkat kebugaran jasmani baik"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000037 "Tingkat kebugaran jasmani cukup"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000038 "Tingkat kebugaran jasmani kurang"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000039 "Borderline"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000040 "Tekanan darah optimal"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000041 "Tekanan darah normal tinggi"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000042 "Hipertensi derajat 3"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000043 "LDL mendekati optimal"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000044 "Kelainan organik"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000045 "Ketergantungan Ringan"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000046 "Ketergantungan Sedang"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000047 "Ketergantungan Berat"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OI000048 "Ketergantungan Total"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OV000298 "Risiko malnutrisi rendah"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OV000299 "Risiko malnutrisi sedang"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/clinical-term where concept is-a #OV000300 "Risiko malnutrisi tinggi"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/examination where concept is-a #X099770 "Rifampisin sensitive"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/examination where concept is-a #X099771 "Rifampisin resistan"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/examination where concept is-a #X099772 "Rifampisin indeterminate"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/examination where concept is-a #IP099352 "defisit neurologis ringan"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/examination where concept is-a #IP099353 "defisit neurologis sedang / cukup berat"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/examination where concept is-a #IP099354 "defisit neurologis berat"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/examination where concept is-a #IP099355 "defisit neurologis sangat berat"
* include codes from system http://terminology.kemkes.go.id/CodeSystem/ObservationInterpretation where concept is-a #BMI-SevereUnder "Severely Underweight"
* include codes from system http://snomed.info/sct where concept is-a #827069000 "Stage 1 hypertension"
* include codes from system http://snomed.info/sct where concept is-a #827068008 "Stage 2 hypertension"
* include codes from system http://snomed.info/sct where concept is-a #56218007 "Systolic hypertension"
* include codes from system http://snomed.info/sct where concept is-a #248311001 "Central obesity"
* include codes from system http://snomed.info/sct where concept is-a #73211009 "Diabetes mellitus"
* include codes from system http://snomed.info/sct where concept is-a #45089002 "Normal vision"
* include codes from system http://snomed.info/sct where concept is-a #397543001 "Mild visual impairment"
* include codes from system http://snomed.info/sct where concept is-a #397542006 "Moderate visual impairment"
* include codes from system http://snomed.info/sct where concept is-a #397541004 "Severe visual impairment"
* include codes from system http://snomed.info/sct where concept is-a #274572000 "Blind right eye"
* include codes from system http://snomed.info/sct where concept is-a #23986001 "Glaucoma"
* include codes from system http://snomed.info/sct where concept is-a #248325000 "Undernourished"
* include codes from system http://snomed.info/sct where concept is-a #248324001 "Well nourished"
* include codes from system http://snomed.info/sct where concept is-a #414915002 "Obese"
* include codes from system http://snomed.info/sct where concept is-a #2004005 "Normal blood pressure"
* include codes from system http://snomed.info/sct where concept is-a #255330009 "Blood pressure rise"
* include codes from system http://snomed.info/sct where concept is-a #860635002 "No anemia present"
* include codes from system http://snomed.info/sct where concept is-a #714628002 "Prediabetes"
* include codes from system http://snomed.info/sct where concept is-a #39021009 "Disorder of refraction"
* include codes from system http://snomed.info/sct where concept is-a #260305007 "1"
* include codes from system http://snomed.info/sct where concept is-a #260306008 "2"
* include codes from system http://snomed.info/sct where concept is-a #260307004 "3"
* include codes from system http://snomed.info/sct where concept is-a #260308009 "4"
* include codes from system http://snomed.info/sct where concept is-a #263865001 "Scanty"
* include codes from system http://snomed.info/sct where concept is-a #264605009 "5"
* include codes from system http://snomed.info/sct where concept is-a #272069004 "Positive integer"
* include codes from system http://snomed.info/sct where concept is-a #76948002 "Severe pain"