ValueSet: CommonUCUMUnits
Id: ucum-common
Title: "Common UCUM units"
Description: "Commonly encountered UCUM units (for purposes of helping populate look ups)."
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:2.16.840.1.113883.4.642.3.3144"
* ^version = "1.0.0"
* ^status = #active
* ^experimental = false
* ^date = "2024-03-09T14:36:19-07:00"
* ^publisher = "Health Level Seven International"
* ^contact.telecom[0].system = #url
* ^contact.telecom[=].value = "http://hl7.org"
* ^contact.telecom[+].system = #email
* ^contact.telecom[=].value = "hq@HL7.org"
* ^copyright = "UCUM is Copyright © 1999-2013 Regenstrief Institute, Inc. and The UCUM Organization,    Indianapolis, IN. All rights reserved. See http://unitsofmeasure.org/trac//wiki/TermsOfUse    for details.  This material derives from the HL7 Terminology THO. THO is copyright ©1989+ Health Level Seven International and is made available under the CC0 designation. For more licensing information see: https://terminology.hl7.org/license"
* UCUM#% "percent"
* UCUM#%/100 "percent / 100"
* UCUM#%[slope] "percent of slope"
* UCUM#/(12.h) "per 12 * hour"
* UCUM#/(2.h) "per 2 hour"
* UCUM#/10*10 "PerTenGiga"
* UCUM#/10*12 "PerTrillion"
* UCUM#/10*3 "per thousand"
* UCUM#/10*4 "per 10 thousand"
* UCUM#/10*6 "PerMillion"
* UCUM#/10*9 "PerBillion"
* UCUM#/100 "per 100"
* UCUM#/100.g "per 100 gram"
* UCUM#/L "per liter"
* UCUM#/U "per enzyme unit"
* UCUM#/[HPF] "per high power field"
* UCUM#/[HPF] "per hpf"
* UCUM#/[IU] "per international unit"
* UCUM#/[LPF] "per low power field"
* UCUM#/[LPF] "per LPF"
* UCUM#/[arb'U] "per arbitrary unit"
* UCUM#/[iU] "per international unit"
* UCUM#/a "/ year"
* UCUM#/cm[H2O] "per centimeter of water"
* UCUM#/d "per day"
* UCUM#/dL "per deciliter"
* UCUM#/g "per gram"
* UCUM#/h "per hour"
* UCUM#/kg "per kilogram"
* UCUM#/m2 "per square meter"
* UCUM#/m3 "per cubic meter"
* UCUM#/mL "per milliliter"
* UCUM#/mg "per milligram"
* UCUM#/min "per minute"
* UCUM#/min/10*3 "per minute per thousand"
* UCUM#/mm "per millimeter"
* UCUM#/mm3 "per cubic millimeter"
* UCUM#/mmol "per millimole"
* UCUM#/mo "per month"
* UCUM#/s "per second"
* UCUM#/uL "per microliter"
* UCUM#/ug "per microgram"
* UCUM#/wk "per week"
* UCUM#1 "1*"
* UCUM#1/d "one per day"
* UCUM#1/min "one per minute"
* UCUM#10* "the number ten for arbitrary powers"
* UCUM#10*-3 "(the number ten for arbitrary powers ^ -3)"
* UCUM#10*-6 "the number ten for arbitrary powers ^ -6"
* UCUM#10*12/L "trillion per liter"
* UCUM#10*3 "Thousand"
* UCUM#10*3.U "Thousand Per * Unit"
* UCUM#10*3/L "Thousand Per Liter"
* UCUM#10*3/mL "Thousand Per MilliLiter"
* UCUM#10*3/uL "Thousands Per MicroLiter"
* UCUM#10*4/uL "10 thousand per microliter"
* UCUM#10*5 "OneHundredThousand"
* UCUM#10*6 "Million"
* UCUM#10*6.U "(the number ten for arbitrary powers ^ 6) * Unit"
* UCUM#10*6.[CFU]/L "million colony forming unit per liter"
* UCUM#10*6.[IU] "million international unit"
* UCUM#10*6.[iU] "MillionInternationalUnit"
* UCUM#10*6.eq/mL "MillionEquivalentsPerMilliLiter"
* UCUM#10*6/(24.h) "million per 24 hour"
* UCUM#10*6/L "million per liter"
* UCUM#10*6/kg "million per kilogram"
* UCUM#10*6/mL "million per milliliter"
* UCUM#10*6/mm3 "(the number ten for arbitrary powers ^ 6) / (millimeter ^ 3)"
* UCUM#10*6/uL "million per microliter"
* UCUM#10*8 "TenToEighth"
* UCUM#10*9/L "billion per liter"
* UCUM#10*9/mL "billion per milliliter"
* UCUM#10*9/uL "billion per microliter"
* UCUM#10.L/(min.m2) "10 liter per minute per square meter"
* UCUM#10.L/min "10 liter per minute"
* UCUM#10.uN.s/(cm.m2) "10 * microNewton * second / centimeter * (meter ^ 2)"
* UCUM#10.uN.s/(cm5.m2) "10 micronewton second per centimeter to the fifth power per square meter"
* UCUM#10.uN.s/cm "10 * microNewton * second / centimeter"
* UCUM#10.uN.s/cm2 "10 * microNewton * second / (centimeter ^ 2)"
* UCUM#10^ "the number ten for arbitrary powers"
* UCUM#24.h "24 hour"
* UCUM#A "Ampère"
* UCUM#A/m "Ampère / meter"
* UCUM#AU "astronomic unit"
* UCUM#Ao "Ångström"
* UCUM#B "bel"
* UCUM#B[SPL] "bel sound pressure"
* UCUM#B[V] "bel volt"
* UCUM#B[W] "bel watt"
* UCUM#B[kW] "bel kilowatt"
* UCUM#B[mV] "bel millivolt"
* UCUM#B[uV] "bel microvolt"
* UCUM#Bd "baud"
* UCUM#Bi "Biot"
* UCUM#Bq "Becquerel"
* UCUM#By "byte"
* UCUM#C "Coulomb"
* UCUM#Cel "degree Celsius"
* UCUM#Ci "CURIE"
* UCUM#F "Farad"
* UCUM#G "Gauss"
* UCUM#GBq "gigaBecquerel"
* UCUM#Gal "Gal"
* UCUM#Gb "Gilbert"
* UCUM#Gy "Gray"
* UCUM#H "Henry"
* UCUM#Hz "Hertz"
* UCUM#J "joule"
* UCUM#J/L "joule per liter"
* UCUM#K "Kelvin"
* UCUM#K/W "Kelvin / Watt"
* UCUM#Ky "Kayser"
* UCUM#L "liter"
* UCUM#L.s2/s "liter * (second ^ 2) / second"
* UCUM#L/(24.h) "liter per 24 hour"
* UCUM#L/(8.h) "liter per 8 hour"
* UCUM#L/(min.m2) "liter per minute per square meter"
* UCUM#L/L "liter per liter"
* UCUM#L/d "liter per day"
* UCUM#L/h "liter per hour"
* UCUM#L/kg "liter per kilogram"
* UCUM#L/min "liter per minute"
* UCUM#L/s "liter / second"
* UCUM#L/s/s2 "liter per second per square second"
* UCUM#Lmb "Lambert"
* UCUM#MBq "megaBecquerel"
* UCUM#Ms "megasecond"
* UCUM#Mx "Maxwell"
* UCUM#N "Newton"
* UCUM#N.cm "Newton centimeter"
* UCUM#N.s "Newton second"
* UCUM#Np "neper"
* UCUM#Oe "Oersted"
* UCUM#Ohm "Ohm"
* UCUM#Ohm.m "Ohm meter"
* UCUM#P "Poise"
* UCUM#Pa "Pascal"
* UCUM#R "Roentgen"
* UCUM#RAD "radiation absorbed dose"
* UCUM#REM "radiation equivalent man"
* UCUM#S "Siemens"
* UCUM#St "Stokes"
* UCUM#Sv "Sievert"
* UCUM#T "Tesla"
* UCUM#U "enzyme Unit"
* UCUM#U/(1.h) "enzyme Unit per 1 hour"
* UCUM#U/(10.g) "enzyme unit per 10 gram"
* UCUM#U/(12.h) "enzyme unit per 12 hour"
* UCUM#U/(18.h) "enzyme Unit per 18 hour"
* UCUM#U/(2.h) "enzyme unit per 2 hour"
* UCUM#U/(24.h) "enzyme unit per 24 hour"
* UCUM#U/10 "enzyme unit per 10"
* UCUM#U/10*10 "enzyme unit per 10 billion"
* UCUM#U/10*12 "enzyme unit per trillion"
* UCUM#U/10*12 "enzyme unit per trillion"
* UCUM#U/10*6 "enzyme unit per million"
* UCUM#U/10*9 "enzyme unit per billion"
* UCUM#U/L "enzyme unit per liter"
* UCUM#U/d "enzyme unit per day"
* UCUM#U/dL "enzyme unit per deciliter"
* UCUM#U/g "enzyme unit per gram"
* UCUM#U/h "enzyme unit per hour"
* UCUM#U/kg "enzyme unit per kilogram"
* UCUM#U/kg/h "Unit / kilogram / hour"
* UCUM#U/mL "enzyme unit per milliliter"
* UCUM#U/min "enzyme unit per minute"
* UCUM#U/mmol "enzyme unit per millimole"
* UCUM#U/mol "enzyme Unit per mole"
* UCUM#U/s "enzyme unit per second"
* UCUM#U/umol "enzyme Unit per micromole"
* UCUM#V "volt"
* UCUM#W "Watt"
* UCUM#Wb "Weber"
* UCUM#[APL'U] "IgA anticardiolipin unit"
* UCUM#[APL'U]/mL "IgA anticardiolipin unit per milliliter"
* UCUM#[AU] "allergy unit"
* UCUM#[Amb'a'1'U] "Amb a 1 units"
* UCUM#[BAU] "bioequivalent allergen unit"
* UCUM#[Btu] "British thermal unit"
* UCUM#[Btu_39] "British thermal unit at 39 °F"
* UCUM#[Btu_59] "British thermal unit at 59 °F"
* UCUM#[Btu_60] "British thermal unit at 60 °F"
* UCUM#[Btu_IT] "international table British thermal unit"
* UCUM#[Btu_m] "mean British thermal unit"
* UCUM#[Btu_th] "thermochemical British thermal unit"
* UCUM#[CCID_50] "CELL CULTURE INFECTIOUS DOSE 50%"
* UCUM#[CFU] "colony forming unit"
* UCUM#[CFU]/L "colony forming unit per liter"
* UCUM#[CFU]/mL "colony forming unit per milliliter"
* UCUM#[Cal] "nutrition label Calories"
* UCUM#[Ch] "French (catheter gauge)"
* UCUM#[D'ag'U] "D-ANTIGEN UNITS"
* UCUM#[FFU] "FOCUS-FORMING UNITS"
* UCUM#[GPL'U] "IgG anticardiolipin unit"
* UCUM#[GPL'U]/mL "IgG anticardiolipin unit per milliliter**"
* UCUM#[G] "Newtonian constant of gravitation"
* UCUM#[HPF] "high power field"
* UCUM#[HP] "horsepower"
* UCUM#[IU] "international unit"
* UCUM#[IU]/(2.h) "international unit per 2 hour"
* UCUM#[IU]/(24.h) "international unit per 24 hour"
* UCUM#[IU]/10*9 "international unit per billion"
* UCUM#[IU]/L "international unit per liter"
* UCUM#[IU]/d "international unit per day"
* UCUM#[IU]/dL "international unit per deciliter"
* UCUM#[IU]/g "international unit per gram"
* UCUM#[IU]/h "international unit per hour"
* UCUM#[IU]/kg "international unit per kilogram"
* UCUM#[IU]/kg/d "international unit per kilogram per day"
* UCUM#[IU]/mL "international unit per milliliter"
* UCUM#[IU]/min "international unit per minute"
* UCUM#[LPF] "low power field"
* UCUM#[Lf] "LIMIT OF FLOCCULATION"
* UCUM#[MET] "metabolic equivalent"
* UCUM#[MPL'U] "IgM anticardiolipin unit"
* UCUM#[MPL'U]/mL "IgM anticardiolipin unit per milliliter**"
* UCUM#[PFU] "PLAQUE-FORMING UNITS"
* UCUM#[PNU] "PROTEIN NITROGEN UNITS"
* UCUM#[PRU] "peripheral vascular resistance unit"
* UCUM#[S] "Svedberg unit"
* UCUM#[TCID_50] "TISSUE CULTURE INFECTIOUS DOSE 50%"
* UCUM#[USP'U] "UNITED STATES PHARMACOPEIA UNIT"
* UCUM#[acr_br] "acre"
* UCUM#[acr_us] "acre"
* UCUM#[arb'U] "arbitrary unit"
* UCUM#[arb'U]/L "arbitary unit / liter"
* UCUM#[arb'U]/mL "arbitrary unit per milliliter"
* UCUM#[bbl_us] "barrel"
* UCUM#[bdsk'U] "Bodansky unit"
* UCUM#[beth'U] "Bethesda unit"
* UCUM#[beth'U] "Bethesda unit"
* UCUM#[bf_i] "board foot"
* UCUM#[bu_br] "bushel"
* UCUM#[bu_us] "bushel"
* UCUM#[c] "velocity of light"
* UCUM#[car_Au] "carat of gold alloys"
* UCUM#[car_m] "metric carat"
* UCUM#[cft_i] "cubic foot"
* UCUM#[ch_br] "Gunter's chain"
* UCUM#[ch_us] "Gunter's chain Surveyor's chain"
* UCUM#[cicero] "cicero Didot's pica"
* UCUM#[cin_i] "cubic inch"
* UCUM#[cml_i] "circular mil"
* UCUM#[cr_i] "cord"
* UCUM#[crd_us] "cord"
* UCUM#[cup_us] "cup"
* UCUM#[cyd_i] "cubic yard"
* UCUM#[degF] "degree Fahrenheit"
* UCUM#[didot] "didot Didot's point"
* UCUM#[diop] "diopter"
* UCUM#[dpt_us] "dry pint"
* UCUM#[dqt_us] "dry quart"
* UCUM#[dr_ap] "dram drachm"
* UCUM#[dr_av] "Dram (US and British)"
* UCUM#[drp] "drop"
* UCUM#[drp]/[HPF] "drop / HPF"
* UCUM#[drp]/h "drop / hour"
* UCUM#[drp]/mL "drop / milliliter"
* UCUM#[drp]/min "drop / minute"
* UCUM#[drp]/s "drop / second"
* UCUM#[dye'U] "Dye unit"
* UCUM#[e] "elementary charge"
* UCUM#[eps_0] "permittivity of vacuum"
* UCUM#[fdr_br] "fluid dram"
* UCUM#[fdr_us] "fluid dram"
* UCUM#[foz_br] "fluid ounce"
* UCUM#[foz_us] "fluid ounce"
* UCUM#[ft_br] "foot"
* UCUM#[ft_i] "Feet"
* UCUM#[ft_us] "foot"
* UCUM#[fth_br] "fathom"
* UCUM#[fth_i] "fathom"
* UCUM#[fth_us] "fathom"
* UCUM#[fur_us] "furlong"
* UCUM#[gal_br] "gallon"
* UCUM#[gal_us] "Queen Anne's wine gallon"
* UCUM#[gal_wi] "historical winchester gallon"
* UCUM#[gil_br] "gill"
* UCUM#[gil_us] "gill"
* UCUM#[gr] "grain"
* UCUM#[h] "Planck constant"
* UCUM#[hd_i] "hand"
* UCUM#[hnsf'U] "Hounsfield unit"
* UCUM#[hp_C] "HOMEOPATHIC POTENCY OF CENTESIMAL SERIES"
* UCUM#[hp_M] "HOMEOPATHIC POTENCY OF MILLESIMAL SERIES"
* UCUM#[hp_Q] "HOMEOPATHIC POTENCY OF QUINTAMILLESIMAL SERIES"
* UCUM#[hp_X] "HOMEOPATHIC POTENCY OF DECIMAL SERIES"
* UCUM#[iU] "international unit"
* UCUM#[iU] "international unit"
* UCUM#[iU]/L "InternationalUnitsPerLiter"
* UCUM#[iU]/dL "InternationalUnitsPerDeciLiter"
* UCUM#[iU]/g "InternationalUnitsPerGram"
* UCUM#[iU]/kg "InternationalUnitsPerKilogram"
* UCUM#[iU]/mL "InternationalUnitsPerMilliLiter"
* UCUM#[in_br] "inch"
* UCUM#[in_i'H2O] "inch (international) of water"
* UCUM#[in_i'Hg] "inch of mercury column"
* UCUM#[in_i] "inch (international)"
* UCUM#[in_us] "inch"
* UCUM#[k] "Boltzmann constant"
* UCUM#[ka'U] "King Armstrong unit"
* UCUM#[kn_br] "knot"
* UCUM#[kn_i] "knot"
* UCUM#[knk'U] "Kunkel unit"
* UCUM#[kp_C] "HOMEOPATHIC POTENCY OF CENTESIMAL KORSAKOVIAN SERIES"
* UCUM#[lb_ap] "pound"
* UCUM#[lb_av] "pound (US and British)"
* UCUM#[lb_tr] "pound"
* UCUM#[lbf_av] "pound force"
* UCUM#[lcwt_av] "long hunderdweight British hundredweight"
* UCUM#[ligne] "ligne French line"
* UCUM#[lk_br] "link for Gunter's chain"
* UCUM#[lk_us] "link for Gunter's chain"
* UCUM#[lne] "line"
* UCUM#[lton_av] "long ton British ton"
* UCUM#[ly] "light-year"
* UCUM#[m_e] "electron mass"
* UCUM#[m_p] "proton mass"
* UCUM#[mclg'U] "Mac Lagan unit"
* UCUM#[mesh_i] "mesh"
* UCUM#[mi_br] "mile"
* UCUM#[mi_i] "statute mile"
* UCUM#[mi_us] "mile"
* UCUM#[mil_i] "mil"
* UCUM#[mil_us] "mil"
* UCUM#[min_br] "minim"
* UCUM#[min_us] "minim"
* UCUM#[mu_0] "permeability of vacuum"
* UCUM#[nmi_br] "nautical mile"
* UCUM#[nmi_i] "nautical mile"
* UCUM#[oz_ap] "ounce (US and British)"
* UCUM#[oz_av] "ounce (US and British)"
* UCUM#[oz_tr] "ounce"
* UCUM#[p'diop] "prism diopter"
* UCUM#[pH] "pH"
* UCUM#[pc_br] "pace"
* UCUM#[pca] "pica"
* UCUM#[pca_pr] "Printer's pica"
* UCUM#[pi] "the number pi"
* UCUM#[pi].rad/min "the number pi * radian / minute"
* UCUM#[pied] "pied French foot"
* UCUM#[pk_br] "peck"
* UCUM#[pk_us] "peck"
* UCUM#[pnt] "point"
* UCUM#[pnt_pr] "Printer's point"
* UCUM#[pouce] "pouce French inch"
* UCUM#[ppb] "part per billion"
* UCUM#[ppm] "part per million"
* UCUM#[ppth] "parts per thousand"
* UCUM#[pptr] "part per trillion"
* UCUM#[pptr] "parts per trillion"
* UCUM#[psi] "pound per square inch"
* UCUM#[pt_br] "pint"
* UCUM#[pt_us] "pint"
* UCUM#[pwt_tr] "pennyweight"
* UCUM#[qt_br] "quart"
* UCUM#[qt_us] "quart"
* UCUM#[rch_us] "Ramden's chain Engineer's chain"
* UCUM#[rd_br] "rod"
* UCUM#[rd_us] "rod"
* UCUM#[rlk_us] "link for Ramden's chain"
* UCUM#[sc_ap] "scruple"
* UCUM#[sct] "section"
* UCUM#[scwt_av] "short hundredweight U.S. hundredweight"
* UCUM#[sft_i] "square foot (international)"
* UCUM#[sin_i] "square inch (international)"
* UCUM#[smgy'U] "Somogyi unit"
* UCUM#[smi_us] "square mile"
* UCUM#[smoot] "Smoot"
* UCUM#[srd_us] "square rod"
* UCUM#[ston_av] "short ton U.S. ton"
* UCUM#[stone_av] "stone British stone"
* UCUM#[syd_i] "square yard"
* UCUM#[tb'U] "tuberculin unit"
* UCUM#[tbs_us] "tablespoon (US)"
* UCUM#[todd'U] "Todd unit"
* UCUM#[todd'U] "Todd unit"
* UCUM#[tsp_us] "teaspoon"
* UCUM#[twp] "township"
* UCUM#[yd_br] "yard"
* UCUM#[yd_i] "yard"
* UCUM#[yd_us] "yard"
* UCUM#a "year"
* UCUM#a_g "mean Gregorian year"
* UCUM#a_j "mean Julian year"
* UCUM#a_t "tropical year"
* UCUM#ag "attogram"
* UCUM#ar "are"
* UCUM#atm "standard atmosphere"
* UCUM#att "technical atmosphere"
* UCUM#b "barn"
* UCUM#bar "bar"
* UCUM#bit "bit"
* UCUM#bit_s "bit"
* UCUM#cL "centiliter"
* UCUM#cP "centiPoise"
* UCUM#cSt "centiStokes"
* UCUM#cal "calorie"
* UCUM#cal_IT "international table calorie"
* UCUM#cal_[15] "calorie at 15 °C"
* UCUM#cal_[20] "calorie at 20 °C"
* UCUM#cal_m "mean calorie"
* UCUM#cal_th "thermochemical calorie"
* UCUM#cd "candela"
* UCUM#cg "centigram"
* UCUM#circ "circle"
* UCUM#cm "centimeter"
* UCUM#cm2 "square centimeter"
* UCUM#cm2/s "square centimeter per second"
* UCUM#cm3 "cubic centimeter"
* UCUM#cm[H2O] "centimeter of water"
* UCUM#cm[H2O]/(s.m) "centimeter of water column / second * meter"
* UCUM#cm[H2O]/L/s "centimeter of water per liter per second"
* UCUM#cm[H2O]/s/m "centimeter of water per second per meter"
* UCUM#cm[Hg] "centimeter of mercury"
* UCUM#d "day"
* UCUM#dB "decibel"
* UCUM#dL "deciliter"
* UCUM#daL/min "dekaliter per minute"
* UCUM#daL/min/m2 "dekaliter per minute per square meter"
* UCUM#deg "degree"
* UCUM#deg/s "degree per second"
* UCUM#dg "decigram"
* UCUM#dm "decimeter"
* UCUM#dm2/s2 "square decimeter per square second"
* UCUM#dyn "dyne"
* UCUM#dyn.s/(cm.m2) "dyne second per centimeter per square meter"
* UCUM#dyn.s/cm "dyne second per centimeter"
* UCUM#eV "electronvolt"
* UCUM#eq "equivalents"
* UCUM#eq/L "equivalents / liter"
* UCUM#eq/mL "equivalents / milliliter"
* UCUM#eq/mmol "equivalents / millimole"
* UCUM#eq/umol "equivalents / micromole"
* UCUM#erg "erg"
* UCUM#fL "femtoliter"
* UCUM#fL/nL "femtoliter / nanoliter"
* UCUM#fg "femtogram"
* UCUM#fm "femtometer"
* UCUM#fmol "femtomole"
* UCUM#fmol/L "femtomole per liter"
* UCUM#fmol/g "femtomole per gram"
* UCUM#fmol/mL "femtomole / milliliter"
* UCUM#fmol/mg "femtomole / milligram"
* UCUM#fmol/mg "femtomole per milligram"
* UCUM#g "gram"
* UCUM#g% "gram percent"
* UCUM#g.m "gram * meter"
* UCUM#g/(100.g) "gram per 100 gram"
* UCUM#g/(12.h) "gram per 12 hour"
* UCUM#g/(24.h) "gram per 24 hour"
* UCUM#g/(3.d) "gram per 3 days"
* UCUM#g/(4.h) "gram per 4 hour"
* UCUM#g/(48.h) "gram per 48 hour"
* UCUM#g/(5.h) "gram per 5 hour"
* UCUM#g/(6.h) "gram per 6 hour"
* UCUM#g/(72.h) "gram per 72 hour"
* UCUM#g/(8.h) "gram / 8 * hour"
* UCUM#g/(8.kg.h) "gram / 8 * kilogram * hour"
* UCUM#g/(kg.h) "gram / kilogram * hour"
* UCUM#g/(kg.min) "gram / kilogram * minute"
* UCUM#g/L "gram per liter"
* UCUM#g/cm3 "gram per cubic centimeter"
* UCUM#g/d "gram per day"
* UCUM#g/dL "gram per deciliter"
* UCUM#g/g "gram per gram"
* UCUM#g/h "gram per hour"
* UCUM#g/h/m2 "gram per hour per square meter"
* UCUM#g/kg "gram per kilogram"
* UCUM#g/kg/(8.h) "gram per  kilogram per 8 hour"
* UCUM#g/kg/d "gram per kilogram per day"
* UCUM#g/kg/h "gram per kilogram per hour"
* UCUM#g/kg/min "gram per kilogram per minute"
* UCUM#g/m2 "grams Per Square Meter"
* UCUM#g/mL "gram per milliliter"
* UCUM#g/mg "gram per milligram"
* UCUM#g/min "gram per minute"
* UCUM#g/mmol "gram per millimole"
* UCUM#g/mol "gram per mole"
* UCUM#gf "gram-force"
* UCUM#gon "gon grade"
* UCUM#h "hour"
* UCUM#hL "hectoliter"
* UCUM#kBq "kiloBecquerel"
* UCUM#kL "kiloliter"
* UCUM#kPa "kiloPascal"
* UCUM#kU "kilo enzyme unit"
* UCUM#kU/L "kiloenzyme Unit per liter"
* UCUM#kU/g "kiloenzyme Unit per gram"
* UCUM#kU/h "kiloUnit / hour"
* UCUM#kU/mL "kilo enzyme unit per milliliter"
* UCUM#k[IU]/L "kilo international unit per liter"
* UCUM#k[IU]/mL "kilo international unit per milliliter"
* UCUM#k[iU]/mL "KiloInternationalUnitsPerMilliLiter"
* UCUM#kat "katal"
* UCUM#kat/L "katal / liter"
* UCUM#kat/kg "katal / kilogram"
* UCUM#kcal "kilocalorie"
* UCUM#kcal/(8.h) "kilocalorie / 8 * hour"
* UCUM#kcal/[oz_av] "kilocalorie per ounce (US & British)"
* UCUM#kcal/d "kilocalorie per day"
* UCUM#kcal/h "kilocalorie per hour"
* UCUM#kcal/kg/(24.h) "kilocalorie per kilogram per 24 hour"
* UCUM#kg "kilogram"
* UCUM#kg.m/s "kilogram meter per second"
* UCUM#kg/(s.m2) "kilogram per second per square meter"
* UCUM#kg/L "kilogram per liter"
* UCUM#kg/h "kilogram per hour"
* UCUM#kg/m2 "kilogram / (meter ^ 2)"
* UCUM#kg/m3 "kilogram / (meter ^ 3)"
* UCUM#kg/min "kilogram / minute"
* UCUM#kg/mol "kilogram per mole"
* UCUM#kg/s "kilogram / second"
* UCUM#km "kilometer"
* UCUM#ks "kilosecond"
* UCUM#lm "lumen"
* UCUM#lm.m2 "lumen square meter"
* UCUM#lm/m2 "lumen / (meter ^ 2)"
* UCUM#lx "lux"
* UCUM#m "meter"
* UCUM#m/s "meter per second"
* UCUM#m/s2 "meter per square second"
* UCUM#m2 "square meter"
* UCUM#m2/s "square meter per second"
* UCUM#m3/s "cubic meter per second"
* UCUM#mA "milliAmpère"
* UCUM#mCi "milliCurie"
* UCUM#mL "milliliter"
* UCUM#mL/(10.h) "milliliter per 10 hour"
* UCUM#mL/(12.h) "milliliter per 12 hour"
* UCUM#mL/(2.h) "milliliter per 2 hour"
* UCUM#mL/(24.h) "milliliter per 24 hour"
* UCUM#mL/(4.h) "milliliter per 4 hour"
* UCUM#mL/(5.h) "milliliter per 5 hour"
* UCUM#mL/(6.h) "milliliter per 6 hour"
* UCUM#mL/(72.h) "milliliter per 72 hour"
* UCUM#mL/(8.h) "milliliter per 8 hour"
* UCUM#mL/(kg.min) "milliliter / kilogram * minute"
* UCUM#mL/L "milliliter per liter"
* UCUM#mL/[sin_i] "milliliter per square inch (international)"
* UCUM#mL/cm[H2O] "milliliter / centimeter of water column"
* UCUM#mL/d "milliliter per day"
* UCUM#mL/dL "milliliter per deciliter"
* UCUM#mL/h "milliliter per hour"
* UCUM#mL/kg "milliliter per kilogram"
* UCUM#mL/kg/(8.h) "milliliter per kilogram per 8 hour"
* UCUM#mL/kg/d "milliliter per kilogram per day"
* UCUM#mL/kg/h "milliliter per kilogram per hour"
* UCUM#mL/kg/min "milliliter per kilogram per minute"
* UCUM#mL/m2 "milliliter per square meter"
* UCUM#mL/mbar "milliliter per millibar"
* UCUM#mL/min "milliliter per minute"
* UCUM#mL/min/(173.10*-2.m2) "milliliter / minute / 173 * (the number ten for arbitrary powers ^ -2) * (meter          ^ 2)"
* UCUM#mL/min/1.73.m2 "milliliter per minute per 1.73 square meter"
* UCUM#mL/min/m2 "milliliter per minute per square meter"
* UCUM#mL/mm "milliliter per millimeter"
* UCUM#mL/s "milliliter per second"
* UCUM#mPa "millipascal"
* UCUM#mPa.s "millipascal second"
* UCUM#mU "millienzyme Unit"
* UCUM#mU/L "millienzyme Unit per liter"
* UCUM#mU/g "millienzyme Unit per gram"
* UCUM#mU/mL "millienzyme Unit per milliliter"
* UCUM#mU/mL/min "millienzyme Unit per milliliter per minute"
* UCUM#mU/mg "milliUnit / milligram"
* UCUM#mU/min "milliUnit / minute"
* UCUM#mU/mmol "millienzyme Unit per millimole"
* UCUM#mV "milliVolt"
* UCUM#m[H2O] "meter of water column"
* UCUM#m[Hg] "meter of mercury column"
* UCUM#m[IU]/L "milli international unit per liter"
* UCUM#m[IU]/mL "milli international unit per milliliter"
* UCUM#m[iU] "milliinternational unit"
* UCUM#mbar "millibar"
* UCUM#mbar.s/L "millibar second per liter"
* UCUM#mbar/L/s "millibar per liter per second"
* UCUM#meq "milliequivalent"
* UCUM#meq/(12.h) "milliequivalent per 12 hour"
* UCUM#meq/(2.h) "milliequivalent per 2 hour"
* UCUM#meq/(24.h) "milliequivalent per 24 hour"
* UCUM#meq/(8.h) "milliequivalent per 8 hour"
* UCUM#meq/(8.h.kg) "milliequivalents / 8 * hour * kilogram"
* UCUM#meq/(kg.d) "milliequivalents / kilogram * day"
* UCUM#meq/L "milliequivalent per liter"
* UCUM#meq/d "milliequivalent per day"
* UCUM#meq/dL "milliequivalent per deciliter"
* UCUM#meq/g "milliequivalent per gram"
* UCUM#meq/h "milliequivalent per hour"
* UCUM#meq/kg "milliequivalent per kilogram"
* UCUM#meq/kg/h "milliequivalent per kilogram per hour"
* UCUM#meq/kg/min "milliequivalents / kilogram / minute"
* UCUM#meq/m2 "milliequivalent per square meter"
* UCUM#meq/mL "milliequivalent per milliliter"
* UCUM#meq/min "milliequivalent per minute"
* UCUM#mg "milligram"
* UCUM#mg/(10.h) "milligram per 10 hour"
* UCUM#mg/(12.h) "milligram per 12 hour"
* UCUM#mg/(18.h) "milligram per 18 hour"
* UCUM#mg/(2.h) "milligram per 2 hour"
* UCUM#mg/(24.h) "milligram per 24 hour"
* UCUM#mg/(6.h) "milligram per 6 hour"
* UCUM#mg/(72.h) "milligram per 72 hour"
* UCUM#mg/(8.h) "milligram per 8 hour"
* UCUM#mg/(8.h.kg) "milligram / 8 * hour * kilogram"
* UCUM#mg/(kg.h) "milligram / kilogram * hour"
* UCUM#mg/L "milligram per liter"
* UCUM#mg/d "milligram per day"
* UCUM#mg/d/(173.10*-2.m2) "milligram / day / 173 * (the number ten for arbitrary powers ^ -2) * (meter ^ 2)"
* UCUM#mg/d/1.73.m2 "milligram per day per 1.73 square meter"
* UCUM#mg/dL "milligram per deciliter"
* UCUM#mg/g "milligram per gram"
* UCUM#mg/h "milligram per hour"
* UCUM#mg/kg "milligram per kilogram"
* UCUM#mg/kg/(24.h) "milligram / kilogram / 24 * hour"
* UCUM#mg/kg/(8.h) "milligram per kilogram per 8 hour"
* UCUM#mg/kg/d "milligram per kilogram per day"
* UCUM#mg/kg/h "milligram per kilogram per hour"
* UCUM#mg/kg/min "milligram per kilogram per minute"
* UCUM#mg/m2 "milligram per square meter"
* UCUM#mg/m3 "milligram per cubic meter"
* UCUM#mg/mL "milligram per milliliter"
* UCUM#mg/mg "milligram per milligram"
* UCUM#mg/min "milligram per minute"
* UCUM#mg/mmol "milligram per millimole"
* UCUM#mg/wk "milligram per week"
* UCUM#mho "mho"
* UCUM#min "minute"
* UCUM#mm "millimeter"
* UCUM#mm/h "millimeter per hour"
* UCUM#mm/min "millimeter per minute"
* UCUM#mm2 "square millimeter"
* UCUM#mm3 "cubic millimeter"
* UCUM#mm[H2O] "millimeter of water"
* UCUM#mm[Hg] "millimeter of mercury"
* UCUM#mmol "millimole"
* UCUM#mmol/(12.h) "millimole per 12 hour"
* UCUM#mmol/(18.h) "millimole per 18 hour"
* UCUM#mmol/(2.h) "millimole per 2 hour"
* UCUM#mmol/(24.h) "millimole per 24 hour"
* UCUM#mmol/(5.h) "millimole per 5 hour"
* UCUM#mmol/(6.h) "millimole per 6 hour"
* UCUM#mmol/(8.h) "millimole per 8 hour"
* UCUM#mmol/(8.h.kg) "millimole / 8 * hour * kilogram"
* UCUM#mmol/L "millimole per liter"
* UCUM#mmol/L/s "millimole per liter per second"
* UCUM#mmol/d "millimole per day"
* UCUM#mmol/dL "millimole per deciliter"
* UCUM#mmol/g "millimole per gram"
* UCUM#mmol/h "millimole per hour"
* UCUM#mmol/h/mg "millimole per hour per milligram"
* UCUM#mmol/kg "millimole per kilogram"
* UCUM#mmol/kg/(8.h) "millimole per kilogram per 8 hour"
* UCUM#mmol/kg/d "millimole per kilogram per day"
* UCUM#mmol/kg/h "millimole per kilogram per hour"
* UCUM#mmol/kg/min "millimole per kilogram per minute"
* UCUM#mmol/m "millimole / meter"
* UCUM#mmol/m2 "millimole per square meter"
* UCUM#mmol/min "millimole per minute"
* UCUM#mmol/mmol "millimole per millimole"
* UCUM#mmol/mol "millimole per mole"
* UCUM#mmol/s/L "millimole per second per liter"
* UCUM#mo "month"
* UCUM#mo_g "mean Gregorian month"
* UCUM#mo_j "mean Julian month"
* UCUM#mo_s "synodal month"
* UCUM#mol "mole"
* UCUM#mol/L "mole per liter"
* UCUM#mol/d "mole per day"
* UCUM#mol/kg "mole per kilogram"
* UCUM#mol/kg/s "mole per kilogram per second"
* UCUM#mol/m3 "mole per cubic meter"
* UCUM#mol/mL "mole per milliliter"
* UCUM#mol/mol "mole per mole"
* UCUM#mol/s "mole per second"
* UCUM#mosm "milliosmole"
* UCUM#mosm/L "milliosmole per liter"
* UCUM#mosm/kg "milliosmole per kilogram"
* UCUM#ms "millisecond"
* UCUM#nCi "nanoCurie"
* UCUM#nL "nanoliter"
* UCUM#nU/mL "nanoenzyme unit per milliliter"
* UCUM#nU "nanoenzyme unit"
* UCUM#ng "nanogram"
* UCUM#ng/(24.h) "nanogram per 24 hour"
* UCUM#ng/(8.h) "nanogram per 8 hour"
* UCUM#ng/(8.h.kg) "nanogram / 8 * hour * kilogram"
* UCUM#ng/(kg.d) "nanogram / kilogram * day"
* UCUM#ng/(kg.h) "nanogram / kilogram * hour"
* UCUM#ng/(kg.min) "nanogram / kilogram * minute"
* UCUM#ng/10*6 "nanogram per million"
* UCUM#ng/L "nanogram per liter"
* UCUM#ng/U "nanogram per enzyme unit"
* UCUM#ng/d "nanogram per day"
* UCUM#ng/dL "nanogram per deciliter"
* UCUM#ng/dL/h "nanogram / deciliter / hour"
* UCUM#ng/g "nanogram per gram"
* UCUM#ng/h "nanogram per hour"
* UCUM#ng/kg "nanogram per kilogram"
* UCUM#ng/kg/(8.h) "nanogram per kilogram per 8 hour"
* UCUM#ng/kg/h "nanogram per kilogram per hour"
* UCUM#ng/kg/min "nanogram per kilogram per minute"
* UCUM#ng/m2 "nanogram per square meter"
* UCUM#ng/mL "nanogram per milliliter"
* UCUM#ng/mL/h "nanogram per milliliter per hour"
* UCUM#ng/mg "nanogram per milligram"
* UCUM#ng/mg/h "nanogram per milligram per hour"
* UCUM#ng/min "nanogram per minute"
* UCUM#ng/s "nanogram per second"
* UCUM#nkat "nanokatal"
* UCUM#nm "nanometer"
* UCUM#nm/s/L "nanometer per second per liter"
* UCUM#nmol "nanomole"
* UCUM#nmol/(24.h) "nanomole per 24 hour"
* UCUM#nmol/L "nanomole per liter"
* UCUM#nmol/L/mmol "nanomole per liter per millimole"
* UCUM#nmol/L/s "nanomole per liter per second"
* UCUM#nmol/d "nanomole per day"
* UCUM#nmol/dL "nanomole per deciliter"
* UCUM#nmol/g "nanomole per gram"
* UCUM#nmol/h/L "nanomole per hour per liter"
* UCUM#nmol/h/mL "nanomole per hour per milliliter"
* UCUM#nmol/h/mg "nanomole per hour per milligram"
* UCUM#nmol/m/mg "nanomole per meter per milligram"
* UCUM#nmol/mL "nanomole per milliliter"
* UCUM#nmol/mL/h "nanomole per milliliter per hour"
* UCUM#nmol/mL/min "nanomole per milliliter per minute"
* UCUM#nmol/mg "nanomole per milligram"
* UCUM#nmol/mg/h "nanomole per milligram per hour"
* UCUM#nmol/min "nanomole per minute"
* UCUM#nmol/min/10*6 "nanomole per minute per million"
* UCUM#nmol/min/mL "nanomole per minute per milliliter"
* UCUM#nmol/min/mg "nanomole per minute per milligram"
* UCUM#nmol/mmol "nanomole per millimole"
* UCUM#nmol/mol "nanomole per mole"
* UCUM#nmol/nmol "nanomole per nanomole"
* UCUM#nmol/s "nanomole per second"
* UCUM#nmol/s/L "nanomole per second per liter"
* UCUM#ns "nanosecond"
* UCUM#osm "osmole"
* UCUM#osm/L "osmole per liter"
* UCUM#osm/kg "osmole per kilogram"
* UCUM#pA "picoampere"
* UCUM#pL "picoliter"
* UCUM#pT "picotesla"
* UCUM#pc "parsec"
* UCUM#pg "picogram"
* UCUM#pg/L "picogram per liter"
* UCUM#pg/dL "picogram per deciliter"
* UCUM#pg/mL "picogram per milliliter"
* UCUM#pg/mg "picogram per milligram"
* UCUM#pg/mm "picogram per millimeter"
* UCUM#ph "phot"
* UCUM#pkat "picokatal"
* UCUM#pm "picometer"
* UCUM#pmol "picomole"
* UCUM#pmol/(24.h) "picomole per 24 hour"
* UCUM#pmol/L "picomole per liter"
* UCUM#pmol/d "picomole per day"
* UCUM#pmol/dL "picomole per deciliter"
* UCUM#pmol/g "picomole per gram"
* UCUM#pmol/h/mL "picomole per hour per milliliter"
* UCUM#pmol/h/mg "picomole per hour per milligram"
* UCUM#pmol/mL "picomole per milliliter"
* UCUM#pmol/mg "picomole per milligram"
* UCUM#pmol/min "picomole per minute"
* UCUM#pmol/min/mg "picomole per minute per milligram"
* UCUM#pmol/mmol "picomole per millimole"
* UCUM#pmol/mol "picomole per mole"
* UCUM#pmol/umol "picomole per micromole"
* UCUM#ps "picosecond"
* UCUM#rad "radian"
* UCUM#s "second"
* UCUM#sb "stilb"
* UCUM#sph "spere"
* UCUM#sr "steradian"
* UCUM#st "stere"
* UCUM#t "tonne"
* UCUM#u "unified atomic mass unit"
* UCUM#uCi "MICROCURIE"
* UCUM#uL "microliter"
* UCUM#uL/(2.h) "microliter per 2 hour"
* UCUM#uL/h "microliter per hour"
* UCUM#uOhm "microOhm"
* UCUM#uU "microUnit"
* UCUM#uU/L "micro enzyme unit per liter"
* UCUM#uU/g "micro enzyme unit per gram"
* UCUM#uU/mL "micro enzyme unit per milliliter"
* UCUM#uV "microvolt"
* UCUM#u[IU] "micro international unit"
* UCUM#u[IU]/L "microinternational unit per liter"
* UCUM#u[IU]/mL "micro international unit per milliliter"
* UCUM#ueq "microequivalents"
* UCUM#ueq/L "microequivalent per liter"
* UCUM#ueq/mL "microequivalent per milliliter"
* UCUM#ug "microgram"
* UCUM#ug/(100.g) "microgram per 100 gram"
* UCUM#ug/(24.h) "microgram per 24 hour"
* UCUM#ug/(8.h) "microgram per 8 hour"
* UCUM#ug/(kg.d) "microgram / kilogram * day"
* UCUM#ug/(kg.h) "microgram / kilogram * hour"
* UCUM#ug/L "microgram per liter"
* UCUM#ug/L/(24.h) "microgram per liter per 24 hour"
* UCUM#ug/[sft_i] "microgram per square foot (international)"
* UCUM#ug/d "microgram per day"
* UCUM#ug/dL "microgram per deciliter"
* UCUM#ug/g "microgram per gram"
* UCUM#ug/h "microgram per hour"
* UCUM#ug/kg "microgram per kilogram"
* UCUM#ug/kg/(8.h) "microgram per kilogram per 8 hour"
* UCUM#ug/kg/d "microgram per kilogram per day"
* UCUM#ug/kg/h "microgram per kilogram per hour"
* UCUM#ug/kg/min "microgram per kilogram per minute"
* UCUM#ug/m2 "microgram per square meter"
* UCUM#ug/m3 "microgram per cubic meter"
* UCUM#ug/mL "microgram per milliliter"
* UCUM#ug/mg "microgram per milligram"
* UCUM#ug/min "microgram per minute"
* UCUM#ug/mmol "microgram per millimole"
* UCUM#ug/ng "microgram per nanogram"
* UCUM#ukat "microkatal"
* UCUM#um "micrometer"
* UCUM#um/s "micrometer per second"
* UCUM#umol "micromole"
* UCUM#umol/(2.h) "micromole per 2 hour"
* UCUM#umol/(24.h) "micromole per 24 hour"
* UCUM#umol/(8.h) "micromole per 8 hour"
* UCUM#umol/L "micromole per liter"
* UCUM#umol/L/h "micromole per liter per hour"
* UCUM#umol/d "micromole per day"
* UCUM#umol/dL "micromole per deciliter"
* UCUM#umol/g "micromole per gram"
* UCUM#umol/h "micromole per hour"
* UCUM#umol/h/L "micromole per hour per liter"
* UCUM#umol/h/g "micromole / hour / gram"
* UCUM#umol/h/mg "micromole per hour per milligram"
* UCUM#umol/kg "micromole per kilogram"
* UCUM#umol/m "micromole / meter"
* UCUM#umol/mL "micromole per milliliter"
* UCUM#umol/mL/min "micromole per milliliter per minute"
* UCUM#umol/mg "micromole per milligram"
* UCUM#umol/min "micromole per minute"
* UCUM#umol/min/L "micromole per minute per liter"
* UCUM#umol/min/g "micromole per minute per gram"
* UCUM#umol/mmol "micromole per millimole"
* UCUM#umol/mol "micromole per mole"
* UCUM#umol/umol "micromole per micromole"
* UCUM#us "microsecond"
* UCUM#wk "week"