CodeSystem: Mddid
Id: mddid
Title: "MDDID"
Description: """Medispan Drug Descriptor ID

Entry autogenerated to support Sources from the UMLS. Full metadata set still incomplete."""
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:2.16.840.1.113883.6.253"
* ^version = "2.0.1"
* ^status = #retired
* ^experimental = false
* ^date = "2021-11-09T10:00:00+10:00"
* ^publisher = "TBD - External Body"
* ^caseSensitive = true
* ^content = #not-present